version: "3.8"
services:
  web:
    build: .
    command: uvicorn app.main:app --proxy-headers --host 0.0.0.0 --port 8000
    volumes:
      - .:/code
    # environment:
    #   - CELERY_BROKER_URL=redis://redis:6379/0
    #   - CELERY_RESULT_BACKEND=redis://redis:6379/0
    ports:
      - 8000:8000
  worker:
    build: .
    command: celery -A app.config worker --loglevel=info
    volumes:
      - .:/code
    # environment:
    #   - CELERY_BROKER_URL=redis://redis:6379/0
    #   - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis
  redis:
    image: redis:7

  flower:
    build: .
    image: mher/flower:0.9.7
    command: celery -A app.config flower
    ports:
      - 5555:5555
    volumes:
      - .:/code
    # environment:
    #   - CELERY_BROKER_URL=redis://redis:6379/0
    #   - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis
